// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msiwikblmajmtqperugi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zaXdpa2JsbWFqbXRxcGVydWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMTk2OTcsImV4cCI6MjA3Mjc5NTY5N30.Y5R_lzSVwDXkQ4VVbIlq_PRWI1Serp7VCd3yl1VjOPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});